# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctw < Formula
  desc "Command-line toolkit for Twitter v2 API"
  homepage "https://github.com/0dayfall/ctw"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/0dayfall/ctw/releases/download/v0.1.0/ctw_0.1.0_darwin_arm64.tar.gz"
      sha256 "" # Will be filled by GoReleaser or manually after creating release
    end
    if Hardware::CPU.intel?
      url "https://github.com/0dayfall/ctw/releases/download/v0.1.0/ctw_0.1.0_darwin_amd64.tar.gz"
      sha256 "" # Will be filled by GoReleaser or manually after creating release
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0dayfall/ctw/releases/download/v0.1.0/ctw_0.1.0_linux_arm64.tar.gz"
      sha256 "" # Will be filled by GoReleaser or manually after creating release
    end
    if Hardware::CPU.intel?
      url "https://github.com/0dayfall/ctw/releases/download/v0.1.0/ctw_0.1.0_linux_amd64.tar.gz"
      sha256 "" # Will be filled by GoReleaser or manually after creating release
    end
  end

  def install
    bin.install "ctw"
  end

  test do
    system "#{bin}/ctw", "--version"
  end
end
